package com.emp.fs.entity;

import java.util.Date;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.name
     *
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.kana
     *
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    private String kana;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.sex
     *
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.birthday
     *
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.address
     *
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.telephone
     *
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.mobile
     *
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.email
     *
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.hireday
     *
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    private Date hireday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.department_id
     *
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    private Integer departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.position_id
     *
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    private Integer positionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.name
     *
     * @return the value of employee.name
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.name
     *
     * @param name the value for employee.name
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.kana
     *
     * @return the value of employee.kana
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    public String getKana() {
        return kana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.kana
     *
     * @param kana the value for employee.kana
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    public void setKana(String kana) {
        this.kana = kana == null ? null : kana.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.sex
     *
     * @return the value of employee.sex
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.sex
     *
     * @param sex the value for employee.sex
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.birthday
     *
     * @return the value of employee.birthday
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.birthday
     *
     * @param birthday the value for employee.birthday
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.address
     *
     * @return the value of employee.address
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.address
     *
     * @param address the value for employee.address
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.telephone
     *
     * @return the value of employee.telephone
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.telephone
     *
     * @param telephone the value for employee.telephone
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.mobile
     *
     * @return the value of employee.mobile
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.mobile
     *
     * @param mobile the value for employee.mobile
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.email
     *
     * @return the value of employee.email
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.email
     *
     * @param email the value for employee.email
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.hireday
     *
     * @return the value of employee.hireday
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    public Date getHireday() {
        return hireday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.hireday
     *
     * @param hireday the value for employee.hireday
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    public void setHireday(Date hireday) {
        this.hireday = hireday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.department_id
     *
     * @return the value of employee.department_id
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.department_id
     *
     * @param departmentId the value for employee.department_id
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.position_id
     *
     * @return the value of employee.position_id
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.position_id
     *
     * @param positionId the value for employee.position_id
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }

    @Override
    public String toString() {
        return "Employee{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", kana='" + kana + '\'' +
                ", sex='" + sex + '\'' +
                ", birthday=" + birthday +
                ", address='" + address + '\'' +
                ", telephone='" + telephone + '\'' +
                ", mobile='" + mobile + '\'' +
                ", email='" + email + '\'' +
                ", hireday=" + hireday +
                ", departmentId=" + departmentId +
                ", positionId=" + positionId +
                '}';
    }
}