package com.emp.fs.dao;

import com.emp.fs.entity.Position;

import java.util.List;

public interface PositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position
     *
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position
     *
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    int insert(Position record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position
     *
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    Position selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position
     *
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    Position selectByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position
     *
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    List<Position> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position
     *
     * @mbg.generated Mon Jul 09 21:33:57 JST 2018
     */
    int updateByPrimaryKey(Position record);
}